### ISSUE TITLE
CSV with Liquid addresses not working

### ISSUE THREAD

**Issue by moneymanolis** [stepansnigirev/specterext-exfund#5]
I tested the Liquid support with this mini CSV ...
```
Address,Label,Amount
vjU2m7F9YaRU8qmYXrCpRxUdiu94ipYDjYdDCQD5zgCnp4p2ba99gBNGT8CV7u9n6LZxAjbWmiFvLHGH,Salary June,12345678
vjTzx1m3RAFRRReP1CYzCE9bzoeTG7xbB9s9r7bSkjMwZv1fvDyKmedAe2Ja63LwSp3uAVnyFAuAhPyH,Conference refund,8274300
tlq1qqw7pdpuxw7vn5ze0jdexwrftw53t7c7ats0r8pclfgaaf7hw72fr7thv80kd38u8p7yje4ldjw0gthaxkac6jqmuzhspy4exk,Specter donation,1000000
tlq1qq085vp87n6zs7lucu5yk24h6ghad2f0sldxjv4a7p5fa3jadeuw7n23q2nqjwn0tptqwaztwvhcr6nk5qltujauy3kfffrf6l,Gym membership,1000
```
... and got this error:
`Server error: Non-compliant json: Unknown unit b2e15d0d7a0c94e4e2ce0fe6e8691b9e451377f6e46e8045a86f7c4b5d4f0f23`

This unit is the result of `dumpassetlabels` for regtest for me. Actually, the error was alternating between the unit for regtest and testnet.

Also, on regtest I get weird symbols:
<img width="800" alt="grafik" src="https://user-images.githubusercontent.com/70536101/185751247-1fcc5374-b25e-488d-90f0-81a914d54fb4.png">

For regtest I used this CSV:
```
Address,Label,Amount
el1qq00wq5vj5f2d8kxglqn8052vmsjx8x2pvluqd8xm33a49u9wwclzwck6dagftfftxsxp46jnzv6pxe90hshguhfm0x26v4ydf,Salary June,12345678
el1qqggqyef3qeav5l5szeyeuuysetucgkysw5cp674j4mcpefa76lpv5s9kp4nzh84avejxgj49n4xmrxe2kdjn22pkjr9pmxxwq,Conference refund,8274300
el1qqw7pdpuxw7vn5ze0jdexwrftw53t7c7ats0r8pclfgaaf7hw72fr7thv80kd38u8p7yje4ldjw0gthaxkac6jm733nf3f82t9,Specter donation,1000000
el1qq085vp87n6zs7lucu5yk24h6ghad2f0sldxjv4a7p5fa3jadeuw7n23q2nqjwn0tptqwaztwvhcr6nk5qltujxefzjsey36hv,Gym membership,1000
```

**Comment by stepansnigirev** [comment]
I was able to reproduce it. This happens when you switch between two liquid nodes (i.e. regtest and testnet). Restarting Specter helps.
Looks like a wrong node is used in Specter - not a currently selected, but the first selected or something.
Weird icons also happen because of that - `assetlabel` filter is fetching label data from a wrong node.

**Comment by stepansnigirev** [comment]
I think this issue is caused by Specter-Desktop code, not by extension. At least I don't see what can go wrong in the extension code... Anyways, if people use only one Liquid node it should work, so I can't say it doesn't work on Liquid - it *almost* works ;)

**Comment by moneymanolis** [comment]
> Looks like a wrong node is used in Specter - not a currently selected, but the first selected or something.

Could very well be, I already had the same impression during testing but this was never an issue. 
I'll test again after a restart.

**Comment by moneymanolis** [comment]
Still getting the same errors.

**Comment by moneymanolis** [comment]
Should be fixed with https://github.com/cryptoadvance/specter-desktop/pull/1851
